export const BANK_OPTIONS = [
    {
        key: 'Tüm Bankalar',
        text: 'Tüm Bankalar',
        value: 'Tüm Bankalar',
        image: {avatar: true, src: require('../src/assets/banks/tum.png')}
      },
      {
        key: 'Kamu Bankaları',
        text: 'Kamu Bankaları',
        value: 'Kamu Bankaları',
        image: {avatar: true, src: require('../src/assets/banks/kamu.png')},
      },
      {
        key: 'Özel Bankalar',
        text: 'Özel Bankalar',
        value: 'Özel Bankalar',
        image: {avatar: true, src: require('../src/assets/banks/ozel.png')}
      },
]

export const MONEY_TYPE_OPTIONS = [
    {
        key: 'TP',
        text: 'TP',
        value: 'TP',
        //image: { avatar: true, src: '../assets/tcmb_logo.png' },
      },
      {
        key: 'YP',
        text: 'YP',
        value: 'YP',
        //image: { avatar: true, src: '../assets/banks/bank.png'  },
      },
      {
        key: 'Toplam',
        text: 'Toplam',
        value: 'Toplam',
        //image: { avatar: true, src: '../assets/banks/özel.png'  },
      },
]

export const CURRENCY_OPTIONS = [
    {
        key: 'TL',
        text: 'TL',
        value: 'TL',
        // image: {avatar: true, src: require('../src/assets/currencies/tl.png')}
      },
      {
        key: 'USD',
        text: 'USD',
        value: 'USD',
        // image: {avatar: true, src: require('../src/assets/currencies/dollar.png')}
      }
]

export const DEFAULT_PARAMS = {
    bank_type: "Tüm Bankalar",
    bank_names: [
      'MERRILL LYNCH YATIRIM BANK A.Ş.', 
      'TÜRKİYE KALKINMA BANKASI A.Ş.', 
      'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 
      'STANDARD CHARTERED YATIRIM BANKASI TÜRK A.Ş.', 
      'TÜRKİYE GARANTİ BANKASI A.Ş.', 
      'DESTEK YATIRIM BANKASI A.S.', 
      'ING BANK A.Ş.', 
      'ZİRAAT KATILIM BANKASI A.Ş.', 
      'VAKIF KATILIM BANKASI A.Ş.', 
      'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 
      'RABOBANK A.Ş.', 'ODEA BANK A.Ş.', 
      'DİLER YATIRIM BANKASI A.Ş.', 
      'İLLER BANKASI A.Ş.', 
      'ŞEKERBANK T.A.Ş.', 
      'JP MORGAN CHASE BANK NATIONAL ASSOCIATION', 
      'TURKLAND BANK A.Ş.', 
      'TÜRKİYE SINAİ KALKINMA BANKASI A.Ş.', 
      'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.',
       'HABİB BANK LİMİTED', 
       'GSD YATIRIM BANKASI A.Ş.', 
       'FİBABANKA A.Ş.', 
       'INTESA SANPAOLO S.P.A.', 
       'SOCIETE GENERALE S.A.', 
       'YAPI VE KREDİ BANKASI A.Ş.',
      'BANK MELLAT', 
      'NUROL YATIRIM BANKASI A.Ş.', 
      'ALTERNATİFBANK A.Ş.', 
      'HSBC BANK A.Ş.', 
      'BANK OF CHINA TURKEY A.Ş.',
       'TÜRKİYE İHRACAT KREDİ BANKASI A.Ş.', 
       'DENİZBANK A.Ş.', 
       'MUFG BANK TURKEY A.Ş.', 
       'TÜRKİYE VAKIFLAR BANKASI T.A.O.', 
       'T.C. ZİRAAT BANKASI A.Ş.', 
       'TÜRKİYE HALK BANKASI A.Ş.', 
       'GOLDEN GLOBAL YATIRIM BANKASI ANONİM ŞİRKETİ', 
       'ANADOLUBANK A.Ş.', 'TURKISH BANK A.Ş.', 
       'TÜRKİYE EMLAK KATILIM BANKASI A.Ş.', 
       'D YATIRIM BANKASI A.Ş.', 
       'TÜRK EKONOMİ BANKASI A.Ş.', 
       'AKBANK T.A.Ş.', 
       'BURGAN BANK A.Ş.', 
       'DEUTSCHE BANK A.Ş.', 
       'QNB FİNANSBANK A.Ş.', 
       'TÜRKİYE İŞ BANKASI A.Ş.', 
       'ARAP TÜRK BANKASI A.Ş.', 
       'CITIBANK A.Ş.', 
       'İSTANBUL TAKAS VE SAKLAMA BANKASI A.Ş.', 
       'BANKPOZİTİF KREDİ VE KALKINMA BANKASI A.Ş.', 
       'ICBC TURKEY BANK A.Ş.', 
       'ROYAL BANK OF SCOTLAND', 
       'PASHA YATIRIM BANKASI A.Ş.', 
       'AKTİF YATIRIM BANKASI A.Ş.'
      ],
    money_type: 'Toplam',
    currency: 'TL',
    start_date: '2022-01-03',
    end_date: '2022-10-07',
    kur: 30,
    pro:false
}

export const chart_tr_configs = {
  defaultLocale: 'tr',
  locales: [{
    name: 'tr',
    options: {
      months: ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
      shortMonths: ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'],
      days: ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'],
      shortDays: ['Paz', 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt'],
      toolbar: {
        download: 'İndir',
        selection: 'Seçim',
        selectionZoom: 'Seçime Yakınlaş',
        zoomIn: 'Yakınlaş',
        zoomOut: 'Uzaklaş',
        pan: 'Kaydır',
        reset: 'Yakınlaştırmayı Sıfırla'
      }
    }
  }]
}

export const COLORS = {
  "red": '#d60033',
  "grey": '#9DB5B2',
  "blue": '#5e8cc6',
  "yellow": "#D4BE9B",
  "darkblue": "#1C3144",
  "purple":"#b594b6",
  "green":"#137547",
  "grey":'#9db5b2',
  "darkgrey":"#666666"
}

export const banks = {
  "Tüm Bankalar": [
    'MERRILL LYNCH YATIRIM BANK A.Ş.', 
    'TÜRKİYE KALKINMA BANKASI A.Ş.', 
    'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 
    'STANDARD CHARTERED YATIRIM BANKASI TÜRK A.Ş.', 
    'TÜRKİYE GARANTİ BANKASI A.Ş.', 
    'DESTEK YATIRIM BANKASI A.S.', 
    'ING BANK A.Ş.', 
    'ZİRAAT KATILIM BANKASI A.Ş.', 
    'VAKIF KATILIM BANKASI A.Ş.', 
    'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 
    'RABOBANK A.Ş.', 'ODEA BANK A.Ş.', 
    'DİLER YATIRIM BANKASI A.Ş.', 
    'İLLER BANKASI A.Ş.', 
    'ŞEKERBANK T.A.Ş.', 
    'JP MORGAN CHASE BANK NATIONAL ASSOCIATION', 
    'TURKLAND BANK A.Ş.', 
    'TÜRKİYE SINAİ KALKINMA BANKASI A.Ş.', 
    'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.',
     'HABİB BANK LİMİTED', 
     'GSD YATIRIM BANKASI A.Ş.', 
     'FİBABANKA A.Ş.', 
     'INTESA SANPAOLO S.P.A.', 
     'SOCIETE GENERALE S.A.', 
     'YAPI VE KREDİ BANKASI A.Ş.',
    'BANK MELLAT', 
    'NUROL YATIRIM BANKASI A.Ş.', 
    'ALTERNATİFBANK A.Ş.', 
    'HSBC BANK A.Ş.', 
    'BANK OF CHINA TURKEY A.Ş.',
     'TÜRKİYE İHRACAT KREDİ BANKASI A.Ş.', 
     'DENİZBANK A.Ş.', 
     'MUFG BANK TURKEY A.Ş.', 
     'TÜRKİYE VAKIFLAR BANKASI T.A.O.', 
     'T.C. ZİRAAT BANKASI A.Ş.', 
     'TÜRKİYE HALK BANKASI A.Ş.', 
     'GOLDEN GLOBAL YATIRIM BANKASI ANONİM ŞİRKETİ', 
     'ANADOLUBANK A.Ş.', 'TURKISH BANK A.Ş.', 
     'TÜRKİYE EMLAK KATILIM BANKASI A.Ş.', 
     'D YATIRIM BANKASI A.Ş.', 
     'TÜRK EKONOMİ BANKASI A.Ş.', 
     'AKBANK T.A.Ş.', 
     'BURGAN BANK A.Ş.', 
     'DEUTSCHE BANK A.Ş.', 
     'QNB FİNANSBANK A.Ş.', 
     'TÜRKİYE İŞ BANKASI A.Ş.', 
     'ARAP TÜRK BANKASI A.Ş.', 
     'CITIBANK A.Ş.', 
     'İSTANBUL TAKAS VE SAKLAMA BANKASI A.Ş.', 
     'BANKPOZİTİF KREDİ VE KALKINMA BANKASI A.Ş.', 
     'ICBC TURKEY BANK A.Ş.', 
     'ROYAL BANK OF SCOTLAND', 
     'PASHA YATIRIM BANKASI A.Ş.', 
     'AKTİF YATIRIM BANKASI A.Ş.'
    ], 
    'Kamu Bankaları': [
      'TÜRKİYE KALKINMA BANKASI A.Ş.', 
      'ZİRAAT KATILIM BANKASI A.Ş.', 
      'VAKIF KATILIM BANKASI A.Ş.', 
      'İLLER BANKASI A.Ş.', 
      'TÜRKİYE İHRACAT KREDİ BANKASI A.Ş.', 
      'TÜRKİYE VAKIFLAR BANKASI T.A.O.', 
      'T.C. ZİRAAT BANKASI A.Ş.', 
      'TÜRKİYE HALK BANKASI A.Ş.', 
      'TÜRKİYE EMLAK KATILIM BANKASI A.Ş.', 
      'İSTANBUL TAKAS VE SAKLAMA BANKASI A.Ş.'
    ], 
    'Özel Bankalar': [
      'MERRILL LYNCH YATIRIM BANK A.Ş.', 
      'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 
      'STANDARD CHARTERED YATIRIM BANKASI TÜRK A.Ş.', 
      'TÜRKİYE GARANTİ BANKASI A.Ş.', 
      'DESTEK YATIRIM BANKASI A.S.', 
      'ING BANK A.Ş.', 
      'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 
      'RABOBANK A.Ş.', 
      'ODEA BANK A.Ş.', 
      'DİLER YATIRIM BANKASI A.Ş.', 
      'ŞEKERBANK T.A.Ş.', 
      'JP MORGAN CHASE BANK NATIONAL ASSOCIATION', 
      'TURKLAND BANK A.Ş.', 
      'TÜRKİYE SINAİ KALKINMA BANKASI A.Ş.', 
      'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 
      'HABİB BANK LİMİTED', 
      'GSD YATIRIM BANKASI A.Ş.',
      'FİBABANKA A.Ş.', 
      'INTESA SANPAOLO S.P.A.', 
      'SOCIETE GENERALE S.A.', 
      'YAPI VE KREDİ BANKASI A.Ş.', 
      'BANK MELLAT', 
      'NUROL YATIRIM BANKASI A.Ş.', 
      'ALTERNATİFBANK A.Ş.', 
      'HSBC BANK A.Ş.', 
      'BANK OF CHINA TURKEY A.Ş.', 
      'DENİZBANK A.Ş.', 
      'MUFG BANK TURKEY A.Ş.', 
      'GOLDEN GLOBAL YATIRIM BANKASI ANONİM ŞİRKETİ', 
      'ANADOLUBANK A.Ş.', 
      'TURKISH BANK A.Ş.', 
      'D YATIRIM BANKASI A.Ş.', 
      'TÜRK EKONOMİ BANKASI A.Ş.', 
      'AKBANK T.A.Ş.', 
      'BURGAN BANK A.Ş.', 
      'DEUTSCHE BANK A.Ş.', 
      'QNB FİNANSBANK A.Ş.', 
      'TÜRKİYE İŞ BANKASI A.Ş.', 
      'ARAP TÜRK BANKASI A.Ş.', 
      'CITIBANK A.Ş.', 
      'BANKPOZİTİF KREDİ VE KALKINMA BANKASI A.Ş.', 
      'ICBC TURKEY BANK A.Ş.', 
      'ROYAL BANK OF SCOTLAND', 
      'PASHA YATIRIM BANKASI A.Ş.', 
      'AKTİF YATIRIM BANKASI A.Ş.'
    ]}

